#define BMP_CALIB_ADDR 0x88
#define BMP_ID_REG 0xD0
#define BMP_RESET 0xE0
#define BMP_STATUS 0xF3
#define BMP_CTRL_MEAS 0xF4
#define BMP_CONFIG 0xF5
#define BMP_PRESS_MSB 0xF7
#define BMP_PRESS_LSB 0xF8
#define BMP_PRESS_XLSB 0xF9
#define BMP_TEMP_MSB 0xFA
#define BMP_TEMP_LSB 0xFB
#define BMP_TEMP_XLSB 0xFC

#define BMP_ID (uint8_t)0x58

#define BMP_ADDRESS_SDO_GROUND 0x76
#define BMP_ADDRESS_SDO_VDD 0x77